/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f8f9ff',
        'surface-dim': '#ccdbf3',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d5e3fc',
        'on-surface': '#0d1c2e',
        'on-surface-variant': '#424654',
        'inverse-surface': '#233144',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#737785',
        'outline-variant': '#c3c6d6',
        'surface-tint': '#0957cc',
        'primary': '#0048af',
        'on-primary': '#ffffff',
        'primary-container': '#1e60d5',
        'on-primary-container': '#dee5ff',
        'inverse-primary': '#b1c5ff',
        'secondary': '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        'tertiary': '#8d3000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b54000',
        'on-tertiary-container': '#ffe0d5',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b1c5ff',
        'on-primary-fixed': '#001946',
        'on-primary-fixed-variant': '#00419e',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#ffb599',
        'on-tertiary-fixed': '#370e00',
        'on-tertiary-fixed-variant': '#7f2b00',
        'background': '#f8f9ff',
        'on-background': '#0d1c2e',
        'surface-variant': '#d5e3fc'
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      },
      spacing: {
        'margin': '1.5rem',
        'margin-desktop': '3rem',
        'margin-mobile': '1rem',
        'gutter': '1.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2rem',
        'space-xxs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem'
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif']
      }
    },
  },
  plugins: [],
}
